apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: docker.pkg.github.com/ganeshdipdumbare/gomicro-ci-cd/helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: CURRENT_GITHUB_SHA
            value: GITHUB_SHA_ID
      imagePullSecrets:
          - name: regcred


